/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:     ["Inter", "system-ui", "sans-serif"],
        headline: ["Space Grotesk", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Public Sans", "sans-serif"],
        mono:     ["DM Mono", "monospace"],
      },
      colors: {
        // Axon brand palette — blue (matches logo)
        brand: {
          50:  "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
        },
        risk: {
          low:      "#22c55e",
          medium:   "#f59e0b",
          high:     "#ef4444",
          critical: "#7c3aed",
        },
        surface: {
          DEFAULT: "#0f172a",
          card:    "#1e293b",
          muted:   "#334155",
        },
        // ── AXON Command Hub (Stitch Design System) ─────────────────────────
        "primary":                    "#6ef6c7",
        "primary-container":          "#4dd9ac",
        "primary-fixed":              "#72facb",
        "primary-fixed-dim":          "#52ddb0",
        "on-primary":                 "#003829",
        "on-primary-container":       "#005b44",
        "on-primary-fixed":           "#002116",
        "on-primary-fixed-variant":   "#00513c",
        "inverse-primary":            "#006c51",
        "secondary":                  "#a4c9ff",
        "secondary-container":        "#0267b8",
        "secondary-fixed":            "#d4e3ff",
        "secondary-fixed-dim":        "#a4c9ff",
        "on-secondary":               "#00315d",
        "on-secondary-container":     "#d6e5ff",
        "on-secondary-fixed":         "#001c39",
        "on-secondary-fixed-variant": "#004883",
        "tertiary":                   "#ffd98e",
        "tertiary-container":         "#f4b91c",
        "tertiary-fixed":             "#ffdf9f",
        "tertiary-fixed-dim":         "#f9bd22",
        "on-tertiary":                "#402d00",
        "on-tertiary-container":      "#674b00",
        "on-tertiary-fixed":          "#261a00",
        "on-tertiary-fixed-variant":  "#5c4300",
        "error":                      "#ffb4ab",
        "error-container":            "#93000a",
        "on-error":                   "#690005",
        "on-error-container":         "#ffdad6",
        "background":                 "#10131b",
        "on-background":              "#e0e2ed",
        "surface-dim":                "#10131b",
        "surface-bright":             "#363941",
        "surface-container-lowest":   "#0b0e15",
        "surface-container-low":      "#181b23",
        "surface-container":          "#1d2027",
        "surface-container-high":     "#272a32",
        "surface-container-highest":  "#32353d",
        "surface-variant":            "#32353d",
        "surface-tint":               "#52ddb0",
        "on-surface":                 "#e0e2ed",
        "on-surface-variant":         "#bbcac1",
        "inverse-surface":            "#e0e2ed",
        "inverse-on-surface":         "#2d3038",
        "outline":                    "#86948c",
        "outline-variant":            "#3c4a43",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in":    "fadeIn 0.3s ease-out",
        "slide-up":   "slideUp 0.4s ease-out",
        "ping":       "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
      keyframes: {
        fadeIn:  { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp: { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
      },
    },
  },
  plugins: [],
}
